"""
Django settings for jy_manager project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '36#@dghy7jzzmroh_l&a^vjhi!4rx5586v%=5ba!v__kjl9t3&'


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = (
    'scheme',
    'easy_thumbnails',
    'filer',
    'mptt',
    'datastream',
    'suit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'event_handover',
    'cleanout',
    'import_export',
    'refused_order',
    'ckeditor',
    # 'rangefilter',
    'date_range_filter',
    'observation',
)


MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
)

ROOT_URLCONF = 'jy_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jy_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/var/www/static/',
]


MEDIA_ROOT = os.path.join(BASE_DIR, "static")
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

DEFAULT_FILE_STORAGE = 'qiniustorage.backends.QiniuStorage'

FILER_STORAGES = {
    'public': {
        'main': {
            'ENGINE': 'qiniustorage.backends.QiniuStorage',
            'OPTIONS': {
                # 'location': MEDIA_ROOT,
                # 'base_url': STATIC_URL,
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX': 'filer_public',
        },
        'thumbnails': {
            'ENGINE': 'qiniustorage.backends.QiniuStorage',
            'OPTIONS': {
                # 'location': MEDIA_ROOT,
                # 'base_url': STATIC_URL,
            },
        },
    },
    'private': {
        'main': {
            'ENGINE': 'qiniustorage.backends.QiniuStorage',
            'OPTIONS': {
                # 'location': MEDIA_ROOT,
                # 'base_url': STATIC_URL,
            },
            'UPLOAD_TO': 'filer.utils.generate_filename.randomized',
            'UPLOAD_TO_PREFIX': 'filer_public',
        },
        'thumbnails': {
            'ENGINE': 'qiniustorage.backends.QiniuStorage',
            'OPTIONS': {
                # 'location': MEDIA_ROOT,
                # 'base_url': STATIC_URL,
            },
        },
    },
}

# Django Suit configuration example
SUIT_CONFIG = {
    # header
    # 'ADMIN_NAME': 'Django Suit',
    # 'HEADER_DATE_FORMAT': 'l, j. F Y',
    # 'HEADER_TIME_FORMAT': 'H:i',

    # forms
    # 'SHOW_REQUIRED_ASTERISK': True,  # Default True
    # 'CONFIRM_UNSAVED_CHANGES': True, # Default True

    # menu
    'SEARCH_URL': '/admin/auth/user/',
    'MENU_ICONS': {
       'sites': 'icon-leaf',
       'auth': 'icon-lock',
    },
    'MENU_OPEN_FIRST_CHILD': True, # Default True
    # 'MENU_EXCLUDE': ('auth.group',),
    'MENU': (
        'sites',
        {'app': 'auth', 'icon': 'icon-lock', 'models': ('user', 'group')},
        {'label': '工作安排', 'icon': 'icon-th', 'models':
            ('scheme.missiontype', 'scheme.mission',
             'scheme.thismonthmission', 'scheme.mymonthmission',
             'scheme.MissionImage',
             )},
        {'label': '退单', 'icon': 'icon-refresh', 'models':  ('refused_order.refusedorder', )},
        {'label': '事件交接', 'icon': 'icon-retweet', 'models':  ('event_handover.HandEvent', )},
        {'label': '数据录入', 'icon': 'icon-qrcode', 'models':  ('datastream.datastream', )},
        {'label': '飞机清洗', 'icon': 'icon-plane', 'models':  ('cleanout.AirCraftCleanOut', )},
        {'label': '故障观察件', 'icon': 'icon-leaf', 'models':  ('observation.Observation', )},
        {'label': '文件管理', 'icon': 'icon-file', 'models':  ('filer.folder', )},

    ),
    'ADMIN_NAME': '部门管理系统'

    # misc
    # 'LIST_PER_PAGE': 15
}



CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'ColorDialog']
        ],
        'height': 160,
    }
}

STATIC_ROOT = '/var/www/project/jy_manager/'
QINIU_ACCESS_KEY = ""
QINIU_SECRET_KEY = ""
QINIU_BUCKET_NAME = ""
QINIU_BUCKET_DOMAIN = ""

ALLOWED_HOSTS = [
    '*', # <B8><B6>
]

try:
    from .local_settings import *
except ImportError:
    pass

